### ISSUE TITLE
Projectile sometimes reflects weirdly off walls

### ISSUE THREAD

**Issue by ronnnnnnnnn** [willowisp01/TankYouVeryMuch#49]
Possibly due to the colliders of the walls?

**Comment by willowisp01** [comment]
Idk bro you tell me

**Comment by ronnnnnnnnn** [comment]
Thanks

**Comment by willowisp01** [comment]
- used physicsmaterial2D to let unity handle the reflections
- don't forget to assign the bullet material to rigidbody else the bullet will not bounce
